SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bills](
	[BillsId] [int] IDENTITY(1,1) NOT NULL,
	[BillId] [int] NOT NULL,
	[Paid] [bit] NOT NULL,
	[BillCycleId] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bills] ADD  CONSTRAINT [PK_BillsId] PRIMARY KEY CLUSTERED 
(
	[BillsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bills]  WITH CHECK ADD  CONSTRAINT [FK_Bills_BillCycleId] FOREIGN KEY([BillCycleId])
REFERENCES [dbo].[BillCycle] ([BillCycleId])
GO
ALTER TABLE [dbo].[Bills] CHECK CONSTRAINT [FK_Bills_BillCycleId]
GO
ALTER TABLE [dbo].[Bills]  WITH CHECK ADD  CONSTRAINT [FK_Bills_BillId] FOREIGN KEY([BillId])
REFERENCES [dbo].[Bill] ([BillId])
GO
ALTER TABLE [dbo].[Bills] CHECK CONSTRAINT [FK_Bills_BillId]
GO
